# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankuser',
            old_name='bankRole',
            new_name='bankrole',
        ),
        migrations.AddField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2019, 1, 18)),
        ),
        migrations.AddField(
            model_name='customer',
            name='idNumber',
            field=models.IntegerField(default=0),
        ),
    ]
