# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0002_auto_20190118_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='idNumber',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
