# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0003_auto_20190118_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 18), null=True),
        ),
    ]
