# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0004_auto_20190118_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='branchOfReg',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bankApp.Branch'),
        ),
    ]
