# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0005_auto_20190118_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=datetime.date(2019, 1, 19), null=True),
        ),
    ]
