# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0006_auto_20190119_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('numberofTransactions', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=datetime.date(2019, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bankUser',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bankApp.BankUser'),
        ),
    ]
