# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0007_auto_20190720_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionday',
            name='date',
            field=models.DateField(),
        ),
    ]
