# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0008_auto_20190720_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='JessSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_transactions_limit', models.IntegerField(default=5)),
                ('rule_one_rank', models.IntegerField(default=20)),
                ('rule_two_rank', models.IntegerField(default=20)),
                ('rule_three_rank', models.IntegerField(default=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionday',
            name='account',
        ),
        migrations.DeleteModel(
            name='TransactionDay',
        ),
    ]
