# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0009_auto_20190720_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
